INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Vaske sig',1);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Gå på toilet ',1);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Kropspleje',1);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Af- og påklædning',1);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Spise',1);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Drikke', 1);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Varetage egen sundhed', 1);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Fødeindtagelse', 1);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Udføre daglige rutiner', 2);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Skaffe sig varer og tjenesteydelser',2);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Lave mad', 2);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Lave husligt arbejde',2);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Ændre kropsstilling', 3);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Forflytte sig', 3);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Løfte og bære', 3);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Gå', 3);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Bevæge sig omkring',3);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Færden i forskellige omgivelser', 3);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Bruge transportmidler', 3);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Udholdenhed ', 3);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Muskelstyrke', 3);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Tilegne sig færdigheder', 4);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Problemløsning', 4);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Anvende kommunikationsudstyr og-teknikker', 4);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Orienteringsevne', 4);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Energi og handlekraft',4);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Hukommelse', 4);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Følelsesfunktioner', 4);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Overordnede kognitive funktioner', 4);
INSERT INTO SubcategoryFA ([Name], [CategoryID]) VALUES ('Have lønnet beskæftigelse', 5);
