INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med personlig pleje', 1);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med daglige aktiviteter', 1);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med mobilitet og bevægelse', 2);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med væskeindtag', 3);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med fødeindtag', 3);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Uhensigtsmæssig vægtændring',3);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med overvægt', 3);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med undervægt', 3);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med kirurgisk sår', 4);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med diabetisk sår', 4);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med cancersår', 4);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med tryksår', 4);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med arterielt sår', 4);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med venøst sår', 4);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med blandingssår', 4);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med traumesår', 4);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Andre problemer med hud og slimhinder', 4);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med kommunikation', 5);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med socialt samvær', 6);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Emotionelle problemer', 6);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med misbrug', 6);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Mentale problemer', 6);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Respirationsproblemer', 7);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Cirkulationsproblemer', 7);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med seksualitet', 8);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Akutte smerter', 9);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Periodevise smerter',9);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Kroniske smerter', 9);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med synssans', 9);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med lugtesans', 9);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med hørelse', 9);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med smagssans', 9);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med følesans', 9);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Døgnrytmeproblemer', 10);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Søvnproblemer', 10);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med hukommelse', 11);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med indsigt i behandlingsformål', 11);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med sygdomsindsigt', 11);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Kognitive problemer', 11);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med vandladning', 12);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med urininkontinens', 12);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med afføringsinkontinens', 12);
INSERT INTO SubcategoryHC ([Name],[CategoryID]) VALUES ('Problemer med mave og tarm', 12);